<a href="https://colab.research.google.com/github/JCaballerot/Deep_learning_program/blob/main/Deep_learning_program/Modulo_II/Lab_InceptionV3_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<h1 align="center"><font size="5">INCEPTION-V3</font></h1>

<h2>Introducción</h2>

En este laboratorio utilizaremos el famoso modelo [Inception-V3](https://keras.io/api/applications/inceptionv3/), un modelo desarrollado por google y brindado a la comunidad cientifica para servir de base de aprendisaje y desarrollo de nuevas herramientas. Nosotros utilizaremos este potente modelo para realizar predicciones sobre imagenes basados en modelos de inteligencia artificial.

<h2>Objetivo</h2>

En este laboratorio, aprenderemos más sobre las aplicaciones de las CNN (Redes neuronales convolucionales).
Esta lección no pretende ser una referencia para<b> aprendizaje automático, aprendizaje profundo, convoluciones</b> o <b>TensorFlow</b>. La intención es dar nociones al usuario sobre estos campos.

<h3> Requisitos previos: </h3>

Conocimientos básicos de Python, Neural Networks, Keras y TensorFlow.

<a id="ref1"></a>
<h2>¿Qué es Inception-V3?</h2>

<b>Inception v3</b>  Es un modelo de reconocimiento de imágenes muy utilizado, el cual se demostró que alcanza una exactitud superior al 78.1% en el conjunto de datos de [ImageNet](http://www.image-net.org/). El modelo representa la culminación de muchas ideas que desarrollaron varios investigadores durante años. Se basa en el documento original: [Reformulación de la arquitectura de Inception para la visión artificial](https://arxiv.org/abs/1512.00567) de Szegedy y otros.

El modelo está formado por bloques de construcción simétricos y asimétricos que incluyen convoluciones, reducción promedio, reducción máxima, concatenaciones, retirados y capas completamente conectadas. La normalización por lotes se usa con frecuencia en todo el modelo y se aplica a las entradas de activación. Las pérdidas se calculan a través de Softmax.

A continuación, se muestra un diagrama de alto nivel del modelo:

<img src="https://cloud.google.com/tpu/docs/images/inceptionv3onc--oview.png" alt="HTML5 Icon" style="width: 600px; height: 800px;">
<div style="text-align: center">Representación gráfica de la arquitectura de InceptionV3 </div>

<h2>Codificando con Tensorflow</h2>

In [ ]:
# Importamos las librerias básicas
import tensorflow as tf
import keras

import matplotlib.pyplot as plt
import numpy as np

El modelo Inception-v3 puede importarse directamente desde la librería de keras usando estos simples pasos:

In [ ]:
from keras.applications.inception_v3 import InceptionV3, decode_predictions
from keras import backend as K

In [ ]:
iv3 = InceptionV3()

96124928/96112376 [==============================] - 1s 0us/step


Listo!, ya tenemos nuestro modelo levantado, ahora veremos un resumen de los componentes del modelo

In [ ]:
print(iv3.summary())

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 299, 299, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 149, 149, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 149, 149, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 149, 149, 32) 0           batch_normalization[0][0]        
_______________________________________________________________________________________

Ahora como siguiente paso necesitamos aplicar nuestro modelo sobre alguna imagen a predecir, para esto cargaremos manualmente la imagen de nuestra preferencia:



In [ ]:
from keras.preprocessing import image
x = image.img_to_array(image.load_img("wisky.jpeg", target_size=(299, 299)))
x.shape

(299, 299, 3)

como se observa, la imagen que cargamos se representa por un tensor de tres dimensiones <b>(pixeles alto , pixeles ancho, 3)</b>

In [ ]:
print(x)

[[[136.  98.  27.]
  [132.  94.  23.]
  [126.  89.  21.]
  ...
  [  1.   1.   1.]
  [  1.   1.   1.]
  [  1.   1.   1.]]

 [[136.  98.  27.]
  [132.  94.  23.]
  [126.  89.  21.]
  ...
  [  1.   1.   1.]
  [  1.   1.   1.]
  [  1.   1.   1.]]

 [[135.  97.  26.]
  [131.  92.  23.]
  [125.  87.  22.]
  ...
  [  1.   1.   1.]
  [  1.   1.   1.]
  [  1.   1.   1.]]

 ...

 [[170. 157. 140.]
  [182. 169. 152.]
  [174. 161. 142.]
  ...
  [155. 102.  50.]
  [147.  92.  36.]
  [152.  98.  38.]]

 [[147. 134. 117.]
  [156. 143. 126.]
  [171. 158. 139.]
  ...
  [153. 100.  50.]
  [153.  98.  42.]
  [154.  99.  42.]]

 [[157. 144. 127.]
  [150. 137. 120.]
  [158. 145. 126.]
  ...
  [161. 108.  58.]
  [161. 106.  52.]
  [161. 106.  50.]]]


Será importantísimo realizar la <b>nomalización</b> de nuestra imagen para poder aplicar el modelo sobre esta

In [ ]:
# cambio de rango de 0-255 a -1 a 1
x /= 255
x -= 0.5
x *= 2

In [ ]:
print(x)

[[[ 0.06666672 -0.23137254 -0.7882353 ]
  [ 0.03529418 -0.26274508 -0.81960785]
  [-0.01176471 -0.30196077 -0.8352941 ]
  ...
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]]

 [[ 0.06666672 -0.23137254 -0.7882353 ]
  [ 0.03529418 -0.26274508 -0.81960785]
  [-0.01176471 -0.30196077 -0.8352941 ]
  ...
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]]

 [[ 0.05882359 -0.23921567 -0.79607844]
  [ 0.02745104 -0.27843136 -0.81960785]
  [-0.01960784 -0.31764704 -0.827451  ]
  ...
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]
  [-0.99215686 -0.99215686 -0.99215686]]

 ...

 [[ 0.33333337  0.2313726   0.09803927]
  [ 0.427451    0.32549024  0.19215691]
  [ 0.36470592  0.26274514  0.11372554]
  ...
  [ 0.21568632 -0.19999999 -0.60784316]
  [ 0.15294123 -0.27843136 -0.7176471 ]
  [ 0.19215691 -0.23137254 -0.7019608 ]]

 [

In [ ]:
x = x.reshape([1, x.shape[0], x.shape[1], x.shape[2]])

Finalmente aplicaremos el modelo sobre nuestra imagen tratada

In [ ]:
y = iv3.predict(x)

In [ ]:
y.shape

(1, 1000)

In [ ]:
y

In [ ]:
decode_predictions(y)

49152/35363 [=========================================] - 0s 0us/step


[[('n02823750', 'beer_glass', 0.6725889),
  ('n03443371', 'goblet', 0.01624658),
  ('n03937543', 'pill_bottle', 0.012932636),
  ('n03916031', 'perfume', 0.011535904),
  ('n07920052', 'espresso', 0.008847027)]]

<a id="ref5"> </a>
<h2> Conclusión </h2>

La aplicación de modelos pre-entrenados es directa y sencilla y nos podrá ayudar en algunos casos, sin embargo si deseamos solucionar un problema específico con Deep Learning deberemos contruir un modelo con nuestra propia data o alguna que nos apoye con el fin.

Como podemos ver, la predicción del modelo es bastante acertada sobre imágenes relativamente sencillas

### Gracias por completar este laboratorio!

# Referencias

https://cloud.google.com/tpu/docs/inception-v3-advanced?hl=es